---

# Taking ideas from https://github.com/jdauphant/ansible-role-vagrant


- name: Get latest available vagrant version 
  script: get_vagrant_latest_version.py
  register: vagrant_version_latest

- name: see if vagrant already installed
  shell: which vagrant
  register: which_vagrant

- name: if vagrant installed check version
  shell: vagrant --version | cut -f2 -d " "
  when: which_vagrant
  register:  vagrant_version_current

- name: do install steps for vagrant if versions don't match
  import_tasks: vagrant_install.yml
  vars:
    vagrant_download_version: "{{ vagrant_version_latest.stdout }}"
  when: ( vagrant_version_current is not defined ) or
        ( vagrant_version_current.stdout != vagrant_version_latest.stdout )

- name: output variable result
  debug: 
    msg: "result: {{ vagrant_version_current.stdout != vagrant_version_latest.stdout }}:{{ vagrant_version_current.stdout }}:{{ vagrant_version_latest.stdout }}"
